#! /bin/sh
### BEGIN INIT INFO
# Provides:          airflow-agent
# Required-Start:    $remote_fs $network
# Required-Stop:     $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start airflow-agent daemon
### END INIT INFO

set -e

NAME=airflow
worker_queue=`hostname -s`
DAEMON=/usr/local/bin/$NAME
#DAEMON_OPT="worker -q $worker_queue > $DIR/worker_$worker_queue.log"
DAEMON_OPT="worker -q $worker_queue > $DIR/worker_$worker_queue.log 2>&1"
DESC="Airflow agent"
USER=dap
export AIRFLOW_HOME=/opt/airflow/airflow_bin
export PYTHONPATH=$PYTHONPATH:/opt/airflow/airflow_bin

test -x $DAEMON || exit 0

DIR=/opt/airflow/airflow_bin/
PID=$DIR/airflow_worker_$worker_queue.pid
RETRY=15

if test ! -d "$DIR"; then
  mkdir -p "$DIR"
  chown -R dap. "$DIR"
fi

export PATH="${PATH:+$PATH:}/usr/sbin:/sbin"

# define LSB log_* functions.
. /lib/lsb/init-functions

case "$1" in
  start)
    log_daemon_msg "Starting $DESC" "$NAME"
    #start-stop-daemon --oknodo --start  --exec $DAEMON $DAEMON_OPT>/dev/null 2>&1
    start-stop-daemon  --background --user $USER --oknodo --start   --make-pidfile  --pidfile $PID  --exec $DAEMON -- $DAEMON_OPT
    case "$?" in
        0) log_end_msg 0 ;;
        *) log_end_msg 1; exit 1 ;;
    esac
    ;;
  stop)
    log_daemon_msg "Stopping $DESC" "$NAME"
    start-stop-daemon --oknodo --stop --pidfile $PID --retry $RETRY
    case "$?" in
        0) log_end_msg 0 ;;
        *) log_end_msg 1; exit 1 ;;
    esac
    ;;
  status)
    status_of_proc -p "$PID" "$DAEMON" "$NAME" && exit 0 || exit $?
    ;;
  restart|force-reload)
    $0 stop
    sleep 3
    $0 start
    ;;
  *)
    echo "Usage: /etc/init.d/$NAME {start|stop|restart|force-reload}" >&2
    exit 1
    ;;
esac

exit 0
